x-networks: &golang-skeleton-networks
  - golang-skeleton-net
x-golang-skeleton-api-port: &golang-skeleton-api-port
  - "80:8080"
x-golang-skeleton-redis-port: &golang-skeleton-redis-port
  - "6379:6379"
x-golang-skeleton-rabbitmq-port: &golang-skeleton-rabbitmq-port
  - "5672:5672"
  - "15672:15672"


version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: golang-skeleton-api
    restart: unless-stopped
    command: sh -c "./main"
    ports: *golang-skeleton-api-port
    networks: *golang-skeleton-networks
  redis:
    image: redis:latest
    container_name: 'redis'
    restart: unless-stopped
    hostname: redis
    ports: *golang-skeleton-redis-port
    networks: *golang-skeleton-networks
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: unless-stopped
    ports: *golang-skeleton-rabbitmq-port
    networks: *golang-skeleton-networks

networks:
  golang-skeleton-net:
