apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ml-development
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: celery-pod
      app: app
  template:
    metadata:
      labels:
        type: celery-pod
        app: app
    spec:
      containers:
        - name: app-celery
          image: "golang-skeleton_ml:latest"
          imagePullPolicy: IfNotPresent # NOT PULL IMAGE
          command: ["/bin/sh","-c"]
          args: ["celery -A tasks worker --loglevel=info --concurrency=2 -E --logfile=logs/celery.log"]


          