apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rabbitmq-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: rabbitmq-pod
      app: app
  template:
    metadata:
      name: app-rabbitmq-pod
      labels:
        type: rabbitmq-pod
        app: app
    spec:
      containers:
        - name: app-rabbitmq
          image: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          ports:
            - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: app-rabbitmq
  labels:
    type: app-rabbitmq-service
    app: app
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    type: rabbitmq-pod
    app: app